[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NITRO_PRESET = "netlify"
SECRETS_SCAN_OMIT_KEYS = "NUXT_SITE_NAME,MONGODB_DB,NUXT_SITE_URL"

[functions]
node_bundler = "esbuild"